### ISSUE TITLE
permission error when running bob build

### ISSUE THREAD

**Issue by jlirochon** [heroku-python/bob-builder#15]
I get the following error when building any runtime :

```
dyno$ bob build libraries/sqlite
dyno$ bob deploy libraries/sqlite
dyno$ bob build runtimes/python-2.7.6

Fetching dependencies... found 1:
  - libraries/sqlite
Traceback (most recent call last):
  File "/app/.heroku/python/bin/bob", line 9, in <module>
    load_entry_point('bob-builder==0.0.5', 'console_scripts', 'bob')()
  File "/app/.heroku/python/lib/python2.7/site-packages/bob/cli.py", line 72, in dispatch
    main()
  File "/app/.heroku/python/lib/python2.7/site-packages/bob/cli.py", line 64, in main
    build(formula)
  File "/app/.heroku/python/lib/python2.7/site-packages/bob/cli.py", line 33, in build
    f.build()
  File "/app/.heroku/python/lib/python2.7/site-packages/bob/models.py", line 112, in build
    self.resolve_deps()
  File "/app/.heroku/python/lib/python2.7/site-packages/bob/models.py", line 106, in resolve_deps
    extract_tree(archive, self.build_path)
  File "/app/.heroku/python/lib/python2.7/site-packages/bob/utils.py", line 85, in extract_tree
    tar.extractall(dir)
  File "/app/.heroku/python/lib/python2.7/tarfile.py", line 2051, in extractall
    self.extract(tarinfo, path)
  File "/app/.heroku/python/lib/python2.7/tarfile.py", line 2088, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/app/.heroku/python/lib/python2.7/tarfile.py", line 2164, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/app/.heroku/python/lib/python2.7/tarfile.py", line 2204, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: '/app/.heroku/python/lib/libpython2.7.a'
```

**Comment by jsanders** [comment]
Yep, I'm getting this too. Arg!

**Comment by hellysmile** [comment]
Getting this too!!!

**Comment by kennethreitz** [comment]
@jsanders @hellysmile @jlirochon sorry for not responding sooner!

You can't run this software on top of the standard Heroku Python Buildpack, as all the paths conflict. Instead, I use the Conda buildpack: https://github.com/kennethreitz/conda-buildpack
