### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by edmorley** [heroku-python/bob-builder#34]
Currently `bob --help` fails with:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/bin/bob", line 7, in <module>
    from bob import cli
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/bob/__init__.py", line 1, in <module>
    from . import cli
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/bob/cli.py", line 20, in <module>
    from .models import Formula
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/bob/models.py", line 33, in <module>
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/os.py", line 982, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
```

See:
https://travis-ci.org/kennethreitz/bob-builder/jobs/237710697#L239

**Comment by sharanraj124** [comment]
we are getting same error. how to solve this issue.
```
~ $ bob build support/build/extensions/no-debug-non-zts-20121212/test-1.6.1
Traceback (most recent call last):
  File "/app/.heroku/python/bin/bob", line 7, in <module>
    from bob import cli
  File "/app/.heroku/python/lib/python3.6/site-packages/bob/__init__.py", line 1, in <module>
    from . import cli
  File "/app/.heroku/python/lib/python3.6/site-packages/bob/cli.py", line 20, in <module>
    from .models import Formula
  File "/app/.heroku/python/lib/python3.6/site-packages/bob/models.py", line 33, in <module>
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
  File "/app/.heroku/python/lib/python3.6/os.py", line 1017, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
```

**Comment by dzuelke** [comment]
Unfortunately, this doesn't work:

```
sys.stdout = os.fdopen(sys.stdout.fileno(), 'wb', 0)
sys.stderr = os.fdopen(sys.stderr.fileno(), 'wb', 0)
```

The result is no more output at all in Python3...
